version: '3.8'
services:
  devcontainer:
    env_file: devcontainer.env
    image: maven:3.9.1
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: gfinger/arcadedb:23.3.1
    restart: unless-stopped
    