version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Client-Dockerfile
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    command: ./bin/server.sh
    working_dir: /arcadedb
    build: 
      context: .
      dockerfile: Arcadedb-Dockerfile
    restart: unless-stopped
    environment:
      JAVA_OPTS: -Darcadedb.server.rootPassword=playwithdata -Darcadedb.ha.enabled=true -Darcadedb.server.plugins=Redis:com.arcadedb.redis.RedisProtocolPlugin,MongoDB:com.arcadedb.mongo.MongoDBProtocolPlugin,Postgres:com.arcadedb.postgres.PostgresProtocolPlugin,GremlinServer:com.arcadedb.server.gremlin.GremlinServerPlugin
