debug: true
org:
    makkiato:
        arcadedb:
            connections:
                testdb:
                    host: localhost
                    port: 2480
                    username: root
                    password: playwithdata

logging:   
    level:
        java:
            net: TRACE
